name: Rust

on:
  push:
    branches:
      - "*"
  pull_request:
  schedule:
    - cron: '5 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build and publish docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: anderender/muslrust
          tag_with_ref: true
