name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
  repository_dispatch:
    types:
      - build-trigger

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      RUST_CHANNEL: stable

    steps:
      - uses: actions/checkout@v2

      - name: Get current time
        uses: 1466587594/get-current-time@v1
        id: current-time
        with:
          format: YYYY-MM-DD

      - name: Get latest version
        run: |
          version=$(curl -s https://static.rust-lang.org/dist/channel-rust-stable.toml | grep -A1 '\[pkg.rust\]' | grep version | grep -oE "[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]")
          echo ::set-env name=RUST_VERSION::${version}

      - name: Build docker and publish
        uses: docker/build-push-action@v1
        env:
          TAG1: "${{ env.RUST_VERSION }}-${{ env.RUST_CHANNEL }}"
          TAG2: "${{ env.RUST_CHANNEL }}-${{ steps.current-time.outputs.formattedTime }}"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: anderender/muslrust
          build_args: CHANNEL=${{ env.RUST_CHANNEL }}
          tags: latest,${{ env.RUST_CHANNEL }},${{ env.TAG1 }},${{ env.TAG2 }}
          push: ${{ github.ref == 'ref/heads/master' }}

