name: Build

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      RUST_CHANNEL: stable

    steps:
      - uses: actions/checkout@v2

      - name: Get current time
        uses: 1466587594/get-current-time@v1
        id: current-time
        with:
          format: YYYY-MM-DD

      - name: Build docker and publish
        uses: docker/build-push-action@v1
        env:
          RUST_DATE: "${{ steps.current-time.outputs.formattedTime }}"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: anderender/muslrust
          build_args: CHANNEL=${{env.RUST_CHANNEL}}
          tags: latest,${{env.RUST_CHANNEL}},${{env.RUST_CHANNEL}}-${{env.RUST_DATE}}
          push: ${{ github.ref == 'ref/heads/master' }}

