name: Check new rust release

on:
  schedule:
    - cron: '4 */8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      RUST_CHANNEL: stable

    steps:
      - name: check new version from rust manifest
        run: |
          current_unix=$(gdate +"%s")
          manifest_url=https://static.rust-lang.org/dist/channel-rust-${RUST_CHANNEL}.toml
          last_date=$(curl ${manifest_url} 2>&1 | grep 'date = ' | cut -d "'" -f2)
          last_datetime=$(curl -v ${manifest_url} 2>&1 | grep 'last-modified:' | awk -F ': ' '{ print $2}')
          last_datetime_unix=$(gdate +"%s" -d "${last_datetime}")
          seconds=$(echo "${current_unix} - ${last_datetime_unix}" | bc) 
          if [ "${seconds}" -le 28800 ]; then
            echo ::set-env name=TRIGGER::true
          fi

      - name: send repository dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: build-trigger
        if: env.TRIGGER == 'true'
